<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Confirm Token' => 'Account Confirm Token',
    'Auth Key' => 'Auth Key',
    'Clients' => 'Clientes',
    'Created At' => 'Facha Creacion',
    'Email' => 'Email',
    'ID' => 'Id',
    'Password Hash' => 'Password Hash',
    'Password Reset Token' => 'Password Reset Token',
    'Phone' => 'Telefono',
    'Status' => 'Estado',
    'Surname' => 'Apellidos',
    'Updated At' => 'Fecha Actualizacion',
    'Username' => 'Nombre Usuario',
    'Are you sure you want to delete this item?' => '',
    'Cd Pais' => '',
    'Codigo' => '',
    'Country Code' => 'Codigo Pais',
    'Create Client' => '',
    'Create Productos' => '',
    'Delete' => '',
    'Id Producto' => '',
    'Name' => '',
    'Nombre' => '',
    'Peso Producto' => '',
    'Product Active Count' => '',
    'Product Count' => '',
    'Productos' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Slug' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Client: {name}' => '',
    'Update Productos: {name}' => '',
    'Verified' => '',
];
