<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clients' => 'Clients',
    'Account Confirm Token' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Client ID' => '',
    'Client Products' => '',
    'Codigo' => '',
    'Create Client' => '',
    'Create Client Products' => '',
    'Create Productin' => '',
    'Create Productos' => '',
    'Created At' => '',
    'Delete' => '',
    'Email' => '',
    'ID' => '',
    'Id Producto' => '',
    'Nombre' => '',
    'Pantry Clients ID' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Phone' => '',
    'Productins' => '',
    'Productos' => '',
    'Productos Codigo' => '',
    'Productos Peso Producto' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Status' => '',
    'Surname' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Client Products: {name}' => '',
    'Update Client: {name}' => '',
    'Update Productin: {name}' => '',
    'Update Productos: {name}' => '',
    'Updated At' => '',
    'Username' => '',
    'View Products' => '',
    'Peso Producto' => '@@@@',
];
