<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clients' => 'Clients',
    'Address' => '',
    'CONTROL PANEL' => '',
    'Client ID' => '',
    'Client Information' => '',
    'Client Products' => '',
    'Clients Products' => '',
    'Companys' => '',
    'Country Code' => '',
    'Created At' => '',
    'Create Client' => '',
    'Create Client Products' => '',
    'Create Productos' => '',
    'Dashboard' => '',
    'Delete' => '',
    'ID' => '',
    'Pantry id' => '',
    'pantry_id' => '@@@@',
    'Peso Producto' => 'General Quantity Product',
    'Phone' => 'Phone',
    'Postal Code' => '',
    'Product Code' => '',
    'Product Name' => '',
    'Product Quantity' => '',
    'Product also added to the general database' => '',
    'Province' => '',
    'province' => '@@Province@@',
    'Search...' => '',
    'Surname' => '',
    'status' => '@@Status@@',
    'Update' => '',
    'Updated At' => '',
    'Update Client: {name}' => '',
    'Username' => '',
    'View Products' => '',
];
